name: CodeCoverage

permissions:
    pull-requests: write
on:
    pull_request:
        branches:
            - master
            - develop

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        env:
            ConnectionStrings__DefaultConnection: "Server=127.0.0.1;Port=3306;Database=test;User ID=root;Password=root;"
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                
            -   name: Create Database
                run: |
                    sudo systemctl start mysql
                    mysql --user="root" --password="root" -e "CREATE DATABASE \`test\` character set UTF8mb4 collate utf8mb4_bin;"
            
            -   name: Setup .NET
                id: setup-dotnet
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: '8.0.x'
            -   name: Restore
                run: dotnet restore
            -   name: Build
                run: dotnet build --no-restore

            -   name: Install coverlet
                run: dotnet tool install --global coverlet.console

            -   name: Run tests and generate Cobertura coverage report
                run: coverlet ./UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --format cobertura --targetargs "test . --no-build" --output ./coverage/coverage.cobertura.xml
                
            -   name: Run tests and generate LCOV coverage report
                run: coverlet ./UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --format lcov --targetargs "test . --no-build" --output ./coverage/lcov.info

            -   name: Html and markdown report
                uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
                with:
                    reports: ./coverage/coverage.cobertura.xml
                    targetdir: 'coveragereport'
                    reporttypes: 'HtmlInline;MarkdownSummaryGithub;Cobertura'
                    verbosity: 'Info'
                    title: 'AuctionAPI Coverage Report'
                    tag: '${{ github.run_number }}_${{ github.run_id }}'
                    toolpath: 'reportgeneratortool'

            -   name: Save html and markdown report artifact
                uses: actions/upload-artifact@v2.2.3
                with:
                    name: html-markdown-coverage-report
                    path: coveragereport
                    
            -   name: Save lcov coverage report as artifact
                uses: actions/upload-artifact@v2
                with:
                    name: lcov-coverage-report
                    path: ./coverage/lcov.info

            -   name: Add Coverage PR Comment
                uses: marocchino/sticky-pull-request-comment@v2
                if: github.event_name == 'pull_request'
                with:
                    header: Coverage Report
                    path: ./coveragereport/SummaryGithub.md

            -   name: Write to Job Summary
                run: cat ./coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
                
            -   name: coveralls
                uses: coverallsapp/github-action@v1.1.1
                with:
                    github-token: ${{secrets.GITHUB_TOKEN }}
                    path-to-lcov: ./coverage/lcov.info
