name: .NET

on:
  push:
    branches:
      - coverage
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      id: setup-dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
      
    # - name : coverlet
    #   uses: b3b00/coverlet-action@1.2.5
    #   with:
    #     testProject: 'UnitTests/UnitTests.csproj'
    #     output: 'lcov.info'
    #     outputFormat: 'lcov'
    #     excludes: '[program]*,[test]test.*'

    - name: Check if lcov.info exists and has content
      run: |
        if [ -s "${{ github.workspace }}/UnitTests/lcov.info" ]; then
          echo "lcov.info exists and is not empty"
        else
          echo "Error: lcov.info does not exist or is empty"
          exit 1
        fi
        
    - name: coveralls      
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
        path-to-lcov: ${{ github.workspace }}/UnitTests/lcov.info
