name: .NET

on:
    pull_request:
        branches:
            - master
            - develop
    push:
        branches:
            - coverage

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup .NET
                id: setup-dotnet
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: '8.0.x'
            -   name: Restore
                run: dotnet restore
            -   name: Build
                run: dotnet build --no-restore

            -   name: Convert Coverage
                run: dotnet tool install --global coverlet.console
            -   run: coverlet ./UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --format cobertura --targetargs "test . --no-build" --output ./coverage/coverage.cobertura.xml

            -   name: Save cobertura coverage report as artifact
                uses: actions/upload-artifact@v2
                with:
                    name: coverage-report
                    path: ./coverage/coverage.cobertura.xml

            -   name: ReportGenerator
                uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
                with:
                    reports: ./coverage/coverage.cobertura.xml
                    targetdir: 'coveragereport'
                    reporttypes: 'HtmlInline;MarkdownSummaryGithub'
                    verbosity: 'Info'
                    title: 'AuctionAPI Coverage Report'
                    tag: '${{ github.run_number }}_${{ github.run_id }}'
                    toolpath: 'reportgeneratortool'

            -   name: Upload coverage report artifact
                uses: actions/upload-artifact@v2.2.3
                with:
                    name: CoverageReport
                    path: coveragereport

            -   name: Add Coverage PR Comment
                uses: marocchino/sticky-pull-request-comment@v2
                if: github.event_name == 'pull_request'
                with:
                    recreate: true
                    path: ./coveragereport/SummaryGithub.md

            -   name: Write to Job Summary
                run: cat ./coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
