name: .NET

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      id: setup-dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Build and run tests with Coverlet
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Save coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: UnitTests/TestResults/*/coverage.cobertura.xml

    - name: Convert Coverage to LCOV
      run: dotnet tool install --global coverlet.console
    - run: coverlet ./UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --format lcov --targetargs "test . --no-build" --output ./coverage/lcov.info

    - name: Save lcov coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report-lcov
        path: ./coverage/lcov.info
        
    - name: coveralls      
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
        path-to-lcov: ./coverage/lcov.info
