name: UnitTests

on:
    push:
        branches:
            - IntegrationTests
    pull_request:
        branches:
            - master
            - develop

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v3
#            -   name: Setup MySQL
#                run: |
#                    sudo apt-get update
#                    sudo apt-get install mysql-server -y
#                    sudo mysql -e "ALTER

            -   name: Create Database
                run: |
                    sudo systemctl start mysql
                    mysql --user="root" --password="root" -e "CREATE DATABASE \`test\` character set UTF8mb4 collate utf8mb4_bin;"
            -   name: Setup .NET
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 8.0.x
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --no-restore
            -   name: Test
                run: dotnet test --no-build --verbosity normal
